#!/bin/sh

export DISPLAY=:0
systemctl --user start polkit-gnome-authentication-agent-1
xset -dpms s off
xset r rate 200 40
xrandr --output eDP-1 --mode "1920x1080" --rate 60.00 2>/dev/null
pkill -f picom 2>/dev/null
picom &
pkill -f dunst 2>/dev/null
dunst &
pkill -f nm-applet 2>/dev/null
nm-applet &
pkill -f libinput-gestures 2>/dev/null
libinput-gestures &
pkill -f copyq 2>/dev/null
copyq --start-server &
