#!/usr/bin/env zsh

# ==============================
#   General aliases
# ==============================
# Navigation
alias d="z"
alias pd="cd -"
alias c="clear"
alias home="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Editors
alias v="vim"
alias n="nvim"
alias nv="neovide"
alias sv="sudo vim"
alias sn="sudo nvim"

# Tmux
alias tns="tmux new -s"
alias ta="tmux attach"
alias td="tmux detach"

# System helpers
alias psa="ps auxf"
alias fdh="fd --hidden"
alias pgrep="ps aux | rg"
alias hg="history | rg"
alias openports="netstat -tulanp"
alias fda="fd --absolute-path"
alias fdah="fd --absolute-path --hidden"

# System control
alias reboot="systemctl reboot"
alias shutnow="shutdown now"
alias logout="loginctl kill-session $XDG_SESSION_ID"
alias restart-dm="sudo systemctl restart display-manager"

# File operations
alias cp="cp -iv"
alias cpr="cp -rv"
alias scp="sudo cp -iv"
alias rmd="rm -rfv"
alias mkdir="mkdir -pv"

# Disk usage
alias diskspace="du -S | sort -n -r | less"
alias folders="du -h --max-depth=1"
alias mountedinfo="df -hT"
alias duf="duf -hide special"

# Permissions & security
alias sha1="openssl sha1"
alias own="sudo chown -R $USER"

# Dev & tools
alias grep="grep --color=auto"
alias rg="rg --color=auto"
alias myip="curl ifconfig.me"
alias bright="brightnessctl set"
alias oc="opencode --port 3000"

# Utilities
alias kssh="kitty +kitten ssh"
alias web="cd /var/www/html"
alias da='date "+%Y-%m-%d %A %T %Z"'
alias ai='ollama run llama3-local'
alias aria2-down='aria2c --conf-path=$HOME/.config/aria2/aria2.conf'

# System Information
alias fetch="fastfetch -c my.jsonc"
alias open="xdg-open"
alias vol="wpctl get-volume @DEFAULT_AUDIO_SINK@"

# ==============================
#   File Listing (eza / ls)
# ==============================
LS_BIN="$(command -v eza || command -v ls)"
if [[ "$LS_BIN" == *eza ]]; then
  alias ls="$LS_BIN --icons"
  alias la="$LS_BIN -A --icons"
  alias lz="$LS_BIN -l -A --icons --header --inode"
  alias lh="$LS_BIN -d .* --icons 2>/dev/null"
  alias tree="$LS_BIN -a --icons --tree"
else
  alias ls="$LS_BIN --color=auto"
  alias la="$LS_BIN -A --color=auto"
  alias lz="$LS_BIN -lhAi --color=auto"
  alias lh="$LS_BIN -d .* 2>/dev/null"
  alias tree="tree -a 2>/dev/null || $LS_BIN -R --color=auto"
fi
