#!/usr/bin/env zsh

if [[ -f ~/env/.config/shell/powerlevel10k/powerlevel10k.zsh-theme ]]; then
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi
    source ~/env/.config/shell/powerlevel10k/powerlevel10k.zsh-theme
    [[ ! -f ~/env/.config/shell/.p10k.zsh ]] || source ~/env/.config/shell/.p10k.zsh
else
    PROMPT='%F{cyan}%n@%m%f %F{yellow}%~%f
%F{green}❯%f '
    RPROMPT='%F{red}%(?..✘ %?)%f'
fi
