#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" ""

# Take colors from Image
matugen image "$IMAGE" -m dark -t scheme-content --source-color-index 0
sleep 2

# Reload
eww kill
eww daemon &
sleep 0.5
eww open hyprbar
kill -10 $(pgrep kitty) 2>/dev/null

notify-send "Theme Applied" ""
