#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# === Set wallpaper ===
TYPES=("fade" "wipe" "wave" "grow" "center" "step")
TRANSITION="${TYPES[$((RANDOM % ${#TYPES[@]}))]}"
ANGLE=$((RANDOM % 360))
awww img "$IMAGE" \
  --transition-type "$TRANSITION" \
  --transition-duration 3 \
  --transition-fps 144 \
  --transition-angle "$ANGLE" \
  --transition-bezier ".42,0,.58,1" \
  --transition-step 1

# Take colors from Image
matugen image "$IMAGE" -m dark -t scheme-content --source-color-index 0

# Reload
hyprctl reload
kill -10 $(pgrep kitty) 2>/dev/null

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
