[config]
contrast = 1.0

[config.wallpaper]
command = 'swww'
arguments = ['img', '--transition-type', 'center', '--transition-step', '15', '--transition-fps', '60']
set = true

[templates.Matugen]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.cache/Matugen/Matugen.colors'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.cache/Matugen/hypr-colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.cache/Matugen/waybar-colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.cache/Matugen/alacritty.toml'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.cache/Matugen/kitty-colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.cache/Matugen/fuzzel-colors.ini'

[templates.json]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.cache/Matugen/colors.json'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
