[config]
contrast = 1.0
caching = false
scheme_type = 'content'
mode = 'dark'
source_color_index = 0

[config.wallpaper]
command = 'waypaper --wallpaper {{ image }}'
set = true

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'pkill -9 -f dunst && dunst & disown'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.cache/Matugen/colors.rasi'

[templates.alacritty]
input_path = '~/.config/matugen/templates/colors.toml'
output_path = '~/.cache/Matugen/colors.toml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.kitty]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.cache/Matugen/colors.conf'

[templates.css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.cache/Matugen/colors.css'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-conf.conf'
output_path = '~/.cache/Matugen/tmux-conf.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
