# ---------- GENERAL ----------
continue=true
file-allocation=trunc
auto-file-renaming=false
summary-interval=60
disk-cache=64M

# ---------- SPEED LIMITS ----------
max-overall-download-limit=2560K
max-overall-upload-limit=256K

# ---------- TORRENT ----------
enable-dht=true
enable-dht6=true
bt-enable-lpd=true
bt-max-peers=80
bt-request-peer-speed-limit=512K
seed-ratio=0.0
seed-time=0

# ---------- NETWORK ----------
socket-recv-buffer-size=1M
