# ---------- GENERAL ----------
file-allocation=trunc
auto-file-renaming=false
summary-interval=60
disk-cache=64M
continue=true

# ---------- SPEED CONTROL ----------
max-overall-download-limit=2.5M
max-overall-upload-limit=256K

# ---------- TORRENT OPTIMIZATION ----------
enable-dht=true
enable-dht6=true
bt-enable-lpd=true
bt-max-peers=80
bt-request-peer-speed-limit=512K
bt-stop-timeout=0

# ---------- UPLOAD CONTROL (VERY IMPORTANT) ----------
bt-upload-slots=8
seed-ratio=0.0
seed-time=0

# ---------- CONNECTION STABILITY ----------
socket-recv-buffer-size=1M
file-allocation=trunc
