# ==========================================
#           MODULAR CONFIGS
# ==========================================
# Source all modular configuration files
source = ~/.config/hypr/modules/monitors.conf         # Monitors Config
source = ~/.config/hypr/modules/enviromentalvars.conf # Environment variables and paths
source = ~/.config/hypr/modules/settings.conf         # General settings and input config
source = ~/.config/hypr/modules/keybinds.conf         # Keyboard shortcuts and bindings
source = ~/.config/hypr/modules/startup.conf          # Startup applications and services
source = ~/.config/hypr/modules/decorations.conf      # Window decorations and styling
source = ~/.config/hypr/modules/windowrules.conf      # Window rules and behaviors
source = ~/.config/hypr/modules/animations.conf       # Fast and Snappy animations
