general {
    hide_cursor            = true
    ignore_empty_input     = true
}

background {
    blur_passes       = 2
    blur_size         = 5
    noise             = 0.005
    contrast          = 0.85
    brightness        = 0.75
}

label {
    text        = cmd[update:60000] echo "<b>$(date +"%H:%M")</b>"
    font_size   = 100
    font_family = Noto Sans
    position    = 0, 170
    halign      = center
    valign      = center
    shadow_passes = 1
}

label {
    text        = cmd[update:300000] echo "$(date +"%A, %d %B")"
    font_size   = 20
    font_family = Noto Sans
    position    = 0, 80
    halign      = center
    valign      = center
}

input-field {
    size        = 300, 50
    outline_thickness  = 2
    dots_size          = 0.26
    font_family        = Noto Sans
    fade_on_empty      = true
    fade_timeout       = 1200
    placeholder_text   = <i>  password</i>
    fail_text          = <i>󰟅  $FAIL</i>
    rounding           = 10
    position           = 0, -210
    halign             = center
    valign             = center
    shadow_passes      = 1
}

label {
    text        = 󰌒  enter to unlock
    font_size   = 11
    font_family = Noto Sans
    position    = 0, -278
    halign      = center
    valign      = center
}

label {
    text        = cmd[update:60000] echo "󰌢  $(hostname -s)"
    font_size   = 11
    font_family = Noto Sans
    position    = 20, 14
    halign      = left
    valign      = bottom
}
