hl.on("hyprland.start", function()
	hl.exec_cmd("dunst")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("wl-paste --type text --watch cliphist store & disown")
	hl.exec_cmd("wl-paste --type image --watch cliphist store & disown")
	hl.exec_cmd("eww kill; eww daemon; sleep 1; eww open hyprbar; eww open locks")
	hl.exec_cmd("sh -c 'sleep 2 && nm-applet --indicator &'")
	hl.exec_cmd("sh -c 'sleep 2 && blueman-applet &'")
end)
