hl.on("hyprland.start", function()
	hl.exec_cmd("dunst")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("waypaper --restore")
	-- hl.exec_cmd("systemctl restart --user emacs.service")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("mkdir -p $HOME/.cache/hyprpaper && hyprpaper")
	hl.exec_cmd("eww kill; eww daemon & sleep 0.5; eww open hyprbar")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
