 # General File Dialogs
windowrule {
    name = general-dialogs
    match:title = ^(Open|Save|Select|Choose|Upload)(.*)$
    float = on
    center = on
    size = 80% 70%
}

# System Utilities
windowrule {
    name = system-utils
    match:class = ^(nm-connection-editor|\.blueman-manager-wrapped|org\.pulseaudio\.pavucontrol|xdg-desktop-portal-gtk)$
    float = on
    center = on
    size = 80% 70%
}

# Authentication Dialogs
windowrule {
    name = auth-dialogs
    match:title = ^(Authentication Required|Unlock|Polkit|Authorize)(.*)$
    float = on
    center = on
    size = 80% 70%
}

# Settings & Preferences Windows
windowrule {
    name = settings-windows
    match:title = ^(Preferences|Settings|Properties|Configure)(.*)$
    float = on
    center = on
    size = 80% 70%
}

# Workspace Bindings
windowrule {
    name = workspace-jetbrains
    match:class = ^(jetbrains-toolbox)$
    workspace = 4
}

windowrule {
    name = workspace-lutris
    match:class = ^(net.lutris.Lutris)$
    workspace = 4
}

windowrule {
    name = workspace-cs2
    match:class = ^(cs2)$
    workspace = 5
}

windowrule {
    name = workspace-steam-app
    match:class = ^(steam_app_default)$
    workspace = 5
}

windowrule {
    name = workspace-vlc
    match:class = ^(vlc)$
    workspace = 6
}

windowrule {
    name = workspace-steam
    match:class = ^(steam)$
    workspace = 8
}

windowrule {
    name = workspace-libreoffice
    match:class = ^(libreoffice-startcenter)$
    workspace = 8
}

# Tearing for CS2
windowrule {
    name = cs2-tearing
    match:class = ^(cs2)$
    immediate = on
}
