# Environment setup
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE

# UI and utilities
exec-once = swww-daemon --format xrgb
exec-once = polkit-kde-authentication-agent-1
exec-once = ~/.local/bin/bar-refresh
exec-once = hypridle
exec-once = dunst

# Clipboard management (Wayland-native)
exec-once = wl-clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
