# Environment
exec-once = dbus-update-activation-environment --systemd --all

# UI
exec-once = dunst
exec-once = hypridle
exec-once = nm-applet
exec-once = waypaper -r
exec-once = polkit-kde-authentication-agent-1
exec-once = mkdir -p $HOME/.cache/hyprpaper && hyprpaper
# exec-once = systemctl restart --user emacs.service

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
