# Bound Window Rules
windowrulev2 = workspace 4, class:^(codium)$
windowrulev2 = workspace 4, class:^(Waydroid)$
windowrulev2 = workspace 4, class:^(jetbrains-toolbox)$
windowrulev2 = workspace 5, class:^(vlc)$
windowrulev2 = workspace 5, class:^(heroic)$
windowrulev2 = workspace 5, class:^(heroicgameslauncher)$
windowrulev2 = workspace 8, class:^(steam)$
windowrulev2 = workspace 8, class:^( steam_app_291550)$
windowrulev2 = workspace 8, class:^(libreoffice-startcenter)$
windowrulev2 = workspace 10, class:^(tutanota-desktop)$
windowrulev2 = workspace 10, class:^(Tutanota)$
