# General
windowrulev2 = float, title:^(Open File|Select a File|File Upload|Choose a file)(.*)$
windowrulev2 = center, title:^(Open File|Select a File|File Upload|Choose a file)(.*)$
windowrulev2 = size 80% 70%, title:^(Open File|Select a File|File Upload|Choose a file)(.*)$
windowrulev2 = float, class:^(org.gnome.Nautilus|org.pulseaudio.pavucontrol)$
windowrulev2 = center, class:^(org.gnome.Nautilus|org.pulseaudio.pavucontrol)$
windowrulev2 = size 80% 70%, class:^(org.gnome.Nautilus|org.pulseaudio.pavucontrol)$

# Authentication
windowrulev2 = float, title:^(Authentication Required|Unlock|Polkit|Authorize)$
windowrulev2 = center, title:^(Authentication Required|Unlock)$
windowrulev2 = size 80% 70%, title:^(Authentication Required)$

# Settings/Preferences
windowrulev2 = float, title:^(Preferences|Settings|Properties|Configure)$
windowrulev2 = center, title:^(Preferences|Settings)$
windowrulev2 = size 80% 70%, title:^(Preferences|Settings)$

# Bound Window Rules
windowrulev2 = workspace 4, class:^(jetbrains-toolbox)$
windowrulev2 = workspace 5, class:^(vlc)$
windowrulev2 = workspace 5, class:^(heroic|heroicgameslauncher)$
windowrulev2 = workspace 8, class:^(steam|steam_app_291550)$
windowrulev2 = workspace 8, class:^(libreoffice-startcenter)$
