scan_timeout = 100
command_timeout = 500

"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
follow_symlinks = false

format = """
$os\
$username\
$directory\
$line_break\
$character\
"""

right_format = """$all"""

[directory]
format = "[ $path ]($style)"
truncation_length = 6
truncate_to_repo = false

[directory.substitutions]
"home" = "󰋜"
"Music" = "󰝚"
"Videos" = "󰕧"
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Pictures" = "󰉏"
"Others" = "󰉋"

[git_branch]
symbol = " (bold fg:red)"
format = "  on [$symbol$branch](bold fg:red)"

[git_status]
format = "[ $staged$modified$renamed$stashed$deleted$untracked$conflicted$ahead_behind ]($style)"

staged = "[+${count} ](bold fg:green)"
modified = "[!${count} ](bold fg:yellow)"
renamed = "[>${count} ](bold fg:yellow)"
deleted = "[-${count} ](bold fg:red)"
untracked = "[?${count} ](bold fg:yellow)"
stashed = "[${count} ](bold fg:yellow)"
conflicted = "[✖${count} ](bold fg:red)"

ahead = "[${count} ](bold fg:red)"
behind = "[${count} ](bold fg:red)"
diverged = "[${ahead_count}${behind_count} ](bold fg:red)"

[os]
disabled = false

[os.symbols]
AIX = "󰻀 "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Cygwin = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
InstantOS = " "
Ios = " "
Kali = " "
Linux = " "
Mabox = " "
Manjaro = " "
Mariner = "󰠳 "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = "󰏗 "
openSUSE = " "
OracleLinux = "󰌷 "
PikaOS = " "
Pop = " "
RaspberryPiOS = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Uos = "󰘚 "
Void = " "
Windows = "󰍲 "
Zorin = " "
Unknown = " "
Macos = "󰌍 "

[python]
symbol = " "
format = "[ $symbol$version ](bold)"

[nodejs]
symbol = " "
format = "[ $symbol$version ](bold)"

[bun]
symbol = " "
format = "[ $symbol$version ](bold)"

[golang]
symbol = " "
format = "[ $symbol$version ](bold)"

[rust]
symbol = " "
format = "[ $symbol$version ](bold)"

[zig]
symbol = " "
format = "[ $symbol$version ](bold)"

[c]
symbol = " "
format = "[ $symbol$version ](bold)"

[cpp]
symbol = " "
format = "[ $symbol$version ](bold)"

[lua]
symbol = " "
format = "[ $symbol$version ](bold)"

[nix_shell]
symbol = " "
format = "[ $symbol$state ](bold)"

[git_state]
format = "[ $state( $progress_current/$progress_total) ](bold)"

[package]
symbol = "󰏗 "
format = "[ $symbol$version ](bold)"

[cmake]
symbol = " "
format = "[ $symbol ](bold)"

[docker_context]
symbol = " "
format = "[ $symbol$context ](bold)"

[username]
show_always = true

[line_break]
disable = true

[character]
success_symbol = "[✔](bold fg:green)"
error_symbol = "[✖](bold fg:red)"
vicmd_symbol = "[](bold fg:yellow)"
