# === General ===
outputs = "All"
layer = "Bottom"
position = "Bottom"

# === Modules ===
[modules]
left = [ [ "appLauncher", "Workspaces" ] ]
center = [ [ "MediaPlayer", "Tempo" ] ]
right = [ "SystemInfo", [ "Privacy", "Settings" ,"Tray" ] ]

# === Workspaces ===
[workspaces]
workspace_names = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]
indicator_format = "NameAndIcons"

# === System Info ===
[system_info]
indicators = [ "DownloadSpeed", "UploadSpeed", "Cpu", "Memory", "MemorySwap", { Disk = "/", Name = "Nix", format = "Fraction" } ]
interval = 10

[system_info.cpu]
format = "Percentage"

[system_info.memory]
format = "Fraction"

[system_info.disk]
format = "Fraction"
mounts = ["/"]

[system_info.threshold_type]
warn_threshold = 60
alert_threshold = 80

# === Media Player ===
[media_player]
max_title_length = 50
indicator_format = "Icon"

# === Tray ===
[tray]
right_click = "menu"

# === Tempo ===
[tempo]
clock_format = "%a %d %b %I:%M %p"
weather_location = { Coordinates = [ 29.9679, 77.5452 ] }
weather_indicator = "Icon"

# === Setttings ===
[settings]
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
hibernate_cmd = "systemctl hibernate"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"
network_indicator_format = "Icon"
peripheral_battery_format = "Time"
battery_format = "IconAndPercentage"
bluetooth_indicator_format = "IconAndValue"
audio_indicator_format = "IconAndPercentage"
brightness_indicator_format = "IconAndPercentage"
microphone_indicator_format = "IconAndPercentage"
indicators = ["IdleInhibitor", "PowerProfile", "Audio", "Microphone", "Bluetooth", "Network", "Vpn", "Brightness", "Battery"]

# === OSD ===
[osd]
enabled = true
timeout = 1500
show_volume_percentage = true
show_brightness_percentage = true

# === Animations ===
[animations]
enabled = false

# === Appearance ===
[appearance]
opacity = 1.0
scale_factor = 1.1
font_name = "Noto Sans"

success_color = "#4FD39B"
warning_color = "#FFC966"
danger_color = "#FF6B8D"
text_color = "#F2EEFF"

workspace_colors = [ "#372E4D", "#F2EEFF", "#B26BFF" ]

[appearance.bar]
surface = "Solid"

[appearance.menu]
backdrop = 0.40

[appearance.primary_color]
base = "#B26BFF"
strong = "#D0A4FF"
weak = "#7C3AED"
text = "#FFFFFF"

[appearance.background_color]
base = "#05040A"
weakest = "#0A0812"
weaker = "#110F1B"
weak = "#171029"
neutral = "#231B38"
strong = "#2B1E52"
stronger = "#372E4D"
strongest = "#4B4263"
text = "#F2EEFF"
