# === General ===
outputs = "All"
layer = "Bottom"
position = "Bottom"

# === Modules ===
[modules]
left = [ [ "appLauncher", "Workspaces" ] ]
center = [ [ "MediaPlayer", "Tempo" ] ]
right = [ "SystemInfo", [ "Privacy", "Settings" ,"Tray" ] ]

# === Workspaces ===
[workspaces]
workspace_names = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]
indicator_format = "NameAndIcons"

# === System Info ===
[system_info]
indicators = [ "DownloadSpeed", "UploadSpeed", "Cpu", "Memory", "MemorySwap", { Disk = "/", Name = "Nix", format = "Fraction" } ]
interval = 10

[system_info.cpu]
format = "Percentage"

[system_info.memory]
format = "Fraction"

[system_info.disk]
format = "Fraction"
mounts = ["/"]

[system_info.threshold_type]
warn_threshold = 60
alert_threshold = 80

# === Media Player ===
[media_player]
max_title_length = 50
indicator_format = "Icon"

# === Tray ===
[tray]
right_click = "menu"

# === Tempo ===
[tempo]
clock_format = "%a %d %b %I:%M %p"
weather_location = { Coordinates = [ 29.9679, 77.5452 ] }
weather_indicator = "Icon"

# === Setttings ===
[settings]
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
hibernate_cmd = "systemctl hibernate"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"
network_indicator_format = "Icon"
peripheral_battery_format = "Time"
battery_format = "IconAndPercentage"
bluetooth_indicator_format = "IconAndValue"
audio_indicator_format = "IconAndPercentage"
brightness_indicator_format = "IconAndPercentage"
microphone_indicator_format = "IconAndPercentage"
indicators = ["IdleInhibitor", "PowerProfile", "Audio", "Microphone", "Bluetooth", "Network", "Vpn", "Brightness", "Battery"]

# === OSD ===
[osd]
enabled = true
timeout = 1500
show_volume_percentage = true
show_brightness_percentage = true

# === Animations ===
[animations]
enabled = false

# === Appearance ===
[appearance]
opacity = 1.0
scale_factor = 1.1
font_name = "Noto Sans"

success_color = "#008000"
warning_color = "#8C8C8C"
danger_color = "#FF0033"
text_color = "#FFFFFF"

workspace_colors = [ "#4D4D4D", "#FFFFFF", "#FF1A4B" ]

[appearance.bar]
surface = "Solid"

[appearance.menu]
backdrop = 0.40

[appearance.primary_color]
base = "#D90429"
strong = "#FF1A4B"
weak = "#8B0000"
text = "#FFFFFF"

[appearance.background_color]
base = "#000000"
weakest = "#080808"
weaker = "#121212"
weak = "#1A1A1A"
neutral = "#262626"
strong = "#333333"
stronger = "#4D4D4D"
strongest = "#666666"
text = "#F2F2F2"
