#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# === Set wallpaper ===
TYPES=("fade" "wipe" "wave" "grow" "center" "step")
TRANSITION="${TYPES[$((RANDOM % ${#TYPES[@]}))]}"
ANGLE=$((RANDOM % 360))
swww img "$IMAGE" \
  --transition-type "$TRANSITION" \
  --transition-duration 3 \
  --transition-fps 144 \
  --transition-angle "$ANGLE" \
  --transition-bezier ".42,0,.58,1" \
  --transition-step 1

# Generate theme with Matugen
matugen image "$IMAGE" -m dark -t scheme-content

if command -v tmux >/dev/null 2>&1; then
  tmux source-file $HOME/.config/tmux/tmux.conf 2>/dev/null
  tmux list-clients -F '#{client_tty}' 2>/dev/null | while read -r tty; do
    tmux refresh-client -S -t "$tty"
  done
fi

# Reload Hyprland
hyprctl reload
$HOME/env/nixos/modules/WM/refreshwaybar
kill -12 $(pgrep kitty)
kill -10 $(pgrep kitty)

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
