#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# Apply new wallpaper
feh --bg-fill "$IMAGE"

# Take colors from Image
wallust run "$IMAGE"

# Reload
kill -10 $(pgrep kitty) 2>/dev/null
qtile cmd-obj -o cmd -f reload_config 2>/dev/null

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
