#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# Apply new wallpaper
feh --bg-fill "$IMAGE"

# Take colors from Image
wallust run "$IMAGE"

mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
[ -f "$HOME/.cache/wallust/gtk3.css" ] && cp "$HOME/.cache/wallust/gtk3.css" "$HOME/.config/gtk-3.0/gtk.css"
[ -f "$HOME/.cache/wallust/gtk4.css" ] && cp "$HOME/.cache/wallust/gtk4.css" "$HOME/.config/gtk-4.0/gtk.css"

# Reload
kill -10 $(pgrep kitty) 2>/dev/null
qtile cmd-obj -o cmd -f reload_config 2>/dev/null

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
